version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: pockettracker
      POSTGRES_PASSWORD: pockettracker
      POSTGRES_USER: pockettracker
    restart: unless-stopped
    volumes:
      - /var/opt/PocketTracker/db:/var/lib/postgresql/data
    networks:
      - netDB

  pocket_tracker:
    image: pocket-tracker:1.7.1
    build: .
    restart: unless-stopped
    environment:
      spring.datasource.url: jdbc:postgresql://postgres/pockettracker
      spring.datasource.driver-class-name: org.postgresql.Driver
      spring.datasource.username: pockettracker
      spring.datasource.password: pockettracker
      TZ: Europe/London
      LANG: en_EN.UTF-8
      LANGUAGE: en_EN.UTF-8
      LC_ALL: en_EN.UTF-8
    volumes:
      - /var/opt/PocketTracker/resources:/opt/PocketTracker/resources
      - /var/opt/PocketTracker/backup:/opt/PocketTracker/backup
      - /var/opt/PocketTracker/config:/opt/PocketTracker/config
    ports:
      - "127.0.0.1:10010:10010"
    networks:
      - netDB

networks:
  netDB:
    driver: bridge
