version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: pockettracker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: pockettracker
    restart: unless-stopped
    volumes:
      - /var/opt/PocketTracker/db:/var/lib/postgresql/data
    networks:
      - netDB

  pocket_tracker:
    image: registry.thecodelabs.de/thecodelabs/pocket-tracker:1.6.5
    restart: unless-stopped
    environment:
      spring.datasource.password: ${POSTGRES_PASSWORD}
      TZ: Europe/Berlin
      LANG: de_DE.UTF-8
      LANGUAGE: de_DE.UTF-8
      LC_ALL: de_DE.UTF-8
    volumes:
      - /var/opt/PocketTracker/resources:/opt/PocketTracker/resources
      - /var/opt/PocketTracker/backup:/opt/PocketTracker/backup
      - /var/opt/PocketTracker/config:/opt/PocketTracker/config
    ports:
      - "127.0.0.1:10010:10010"
    networks:
      - netDB

networks:
  netDB:
    driver: bridge
