[#ftl]
[#-- @implicitly included --]
[#-- @ftlroot "templates" --]
[#-- @ftlvariable name="_csrf" type="org.springframework.security.web.csrf.CsrfToken" --]
[#-- @ftlvariable name="showService" type="de.thecodelabs.pockettracker.show.ShowService" --]
