[#ftl]
[#-- @implicitly included --]
[#-- @ftlroot "templates" --]
[#-- @ftlvariable name="_csrf" type="org.springframework.security.web.csrf.CsrfToken" --]
[#-- @ftlvariable name="toast" type="de.thecodelabs.pockettracker.utils.Toast" --]
[#-- @ftlvariable name="showService" type="de.thecodelabs.pockettracker.show.ShowService" --]
[#-- @ftlvariable name="userService" type="de.thecodelabs.pockettracker.user.service.UserService" --]
[#-- @ftlvariable name="currentUser" type="de.thecodelabs.pockettracker.user.model.User" --]
[#-- @ftlvariable name="userRoles" type="java.util.List<de.thecodelabs.pockettracker.user.model.UserRole>" --]
